baseurl = "https://blog.lovinator.space/"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
theme = "cocoa"
author = "TheLovinator"
title = "blog.lovinator.space"
pygmentsuseclasses = false
# disqusshortname     = "lovinator" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics = "UA-104489595-1"

[permalinks]
blog = "blog/:slug/"

[[menu.main]]
name = "blog"
weight = -120
identifier = "blog"
url = "/blog/"

[[menu.main]]
name = "license"
weight = -110
identifier = "license"
url = "/license/"

[[menu.main]]
name = "about"
weight = -100
identifier = "about"
url = "/about/"

[params]
include_rss = true
latestpostscount = 15
i18n_flags = false
author = "TheLovinator"
cachebuster = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Rocket ship builder, pizza expert, loves the Giants, parent."
email = "tlovinator@gmail.com"
extracssfiles = ["/css/override.css"]
faviconfile = "favicon.ico"
github = "https://github.com/TheLovinator1"
lang = "en"
noshowreadtime = false
selfintro = ""

avatar = "img/profile.png"

steam = "https://steamcommunity.com/profiles/76561198021760046"
